# Header
menu:
  4-6 Breathing (start here): /4-6-breathing/
  Box Breathing: /box-breathing/
  Guided Meditation: /

# Title on top left of menu. Leave empty to use main blog title
menu_title: QuietKit

# URL of the Home page image
index_cover: /img/road-curve-rainy-600px-tall.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-72171895-1

# Addthis ID
addthis:

# set your own favicon
favicon: /img/quietkit-fav-icon-192-192.png

# Social Accounts
twitter_url: https://twitter.com/QuietKitApp
twitter_handle:
facebook_url:
github_url:
gitlab_url:
linkedin_url:
mailto: johneturner@gmail.com
